version: '3.7'

services:
# Movie Service
  web:
    build: ./app
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./app/:/app/
    ports:
      - 8001:8000
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://username:password@db/db
    depends_on:
      - db

  db:
    image: postgres:12.1-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db

# Nginx
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

# Volumes
volumes:
  db_data:
